### ISSUE TITLE
How to transcribe the podcast using the oTranscribe website

### ISSUE THREAD

**Issue by bvanrijn** [unicorn-meta-zoo/unicorn-meta-zoo.github.io#2]
For the [episode 3 transcript](https://github.com/unicorn-meta-zoo/unicorn-meta-zoo.github.io/wiki/How-do-we-grade-questions%3F-%5BTranscript%5D), I've been using [oTranscribe](https://otranscribe.com). It works pretty well!

Here's what I did:

1. [Download the recording](https://dts.podtrac.com/redirect.mp3/unicorn-meta-zoo.github.io/episodes/question-grade.mp3)
2. Copy and paste the [transcript](https://github.com/unicorn-meta-zoo/unicorn-meta-zoo.github.io/wiki/How-do-we-grade-questions%3F-%5BTranscript%5D) (the rendered Markdown, not the source) into the document on the oTranscribe website.
3. Click "Choose an audio or video file" and upload the podcast audio.

 Let me know if anything is unclear. Happy transcribing!

**Comment by bvanrijn** [comment]
@jericson maybe we could add this to the wiki?

**Comment by jericson** [comment]
I love it! I'm going to try it out the next time I try my hand at transcription. I've added [a page to the wiki](https://github.com/unicorn-meta-zoo/unicorn-meta-zoo.github.io/wiki/Tools-to-help-transcribing).
