### ISSUE TITLE
Transcript of "How do we grade questions" not finished?

### ISSUE THREAD

**Issue by fzyzcjy** [unicorn-meta-zoo/unicorn-meta-zoo.github.io#3]
Thanks very much for providing transcripts! I wonder whether the transcript of the eps #3 will be finished in the future? Thanks!

**Comment by jericson** [comment]
It depends entirely on volunteer effort, so I don't rightly know. I'm not sure if it'll help, but there is [a way to get an automated transcript from YouTube](https://github.com/unicorn-meta-zoo/unicorn-meta-zoo.github.io/wiki/Tools-to-help-transcribing#youtube-automatic-transcription).

**Comment by fzyzcjy** [comment]
Thanks and add oil!
